AllCops:
  TargetRubyVersion: 2.7

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 160

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: [is]

Naming/VariableNumber:
  Exclude:
    - test/**/*.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
