# frozen_string_literal: true

require 'haptic/rails/builder'
require 'haptic/rails/configuration'
require 'haptic/rails/dialog_builder'
require 'haptic/rails/dropdown_builder'
require 'haptic/rails/dropdown_dialog_builder'
require 'haptic/rails/dropdown_menu_builder'
require 'haptic/rails/engine'
require 'haptic/rails/field_options'
require 'haptic/rails/form_builder'
require 'haptic/rails/helpers'
require 'haptic/rails/menu_builder'
require 'haptic/rails/nav_builder'
require 'haptic/rails/table_builder'
require 'haptic/rails/table_row_builder'
require 'haptic/rails/version'
